exclude: .*venv.*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
    -   id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: "21.6b0"
    hooks:
      - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: "5.8.0"
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910"
    hooks:
    - id: mypy
